In [1]:
# Reference: https://www.ritchieng.com/machine-learning-multinomial-naive-bayes-vectorization/

#Importo as bibliotecas necessárias
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, roc_curve, auc
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.pipeline import make_pipeline

#Biblioteca do Naive Bayes 
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB

In [2]:
#Criação de features e labels
x_train = np.array(['Chinese Beijing Chinese',
'Chinese Chinese Shanghai',
'Chinese Macao',
'Tokyo Japan Chinese'])

x_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])

y_train = np.array(['china','china','china','not china'])

# Bernoulli

In [3]:
#O texto é convertido em uma matrix (representação numérica) binária (com a presença ou não de tal elemento)
vect = CountVectorizer(binary=True)

#O vocabulário da YRL é aprendido e convertido em uma matriz.
x_train_dtm = vect.fit_transform(x_train)

In [4]:
#Instancio o objeto Bernoulli NB
nb = BernoulliNB(binarize=None)

In [5]:
#O classificador Bernoulli NB é treinado com os exemplos e labels de treinamento.
nb.fit(x_train_dtm, y_train)

BernoulliNB(alpha=1.0, binarize=None, class_prior=None, fit_prior=True)

In [6]:
print(vect.get_feature_names())
print(x_train_dtm.toarray())

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
[[1 1 0 0 0 0]
 [0 1 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]


In [7]:
x_test_dtm = vect.transform(x_test)

ypb = nb.predict(x_test_dtm)

print(ypb)

['not china']


In [8]:
print(x_test_dtm.toarray())

[[0 1 1 0 0 1]]


# Multinomial

In [9]:
vect = CountVectorizer()

x_train_dtm = vect.fit_transform(x_train)

print(vect.get_feature_names())
print(x_train_dtm.toarray())

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
[[1 2 0 0 0 0]
 [0 2 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]


In [10]:
mtn = MultinomialNB()

In [11]:
mtn.fit(x_train_dtm, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [12]:
x_test_dtm = vect.transform(x_test)

ypm = mtn.predict(x_test_dtm)

print(ypm)

['china']


In [13]:
print(x_test_dtm.toarray())

[[0 3 1 0 0 1]]
